### ISSUE TITLE
Add TypeScript-compatible static typing for `config` object

### ISSUE THREAD

**Issue by chapati23** [strong-config/node#1]
## Tasks
- [x] Swap out flow for TypeScript
- [x] Get type-checking working at compile-time 
- [x] Get type-checking working at run-time
- [ ] Document new approach in README

## Current Approach
We currently auto-generate flow types by:
1. Reading the config's [JSON schema](https://json-schema.org)
1. Converting it into flow typings using [json-schema-to-flow-type](https://www.npmjs.com/package/json-schema-to-flow-type).
1. Writing it into a a `.flow` file

For TypeScript, we have the option to re-think and improve this approach.

### Drawbacks of Current Approach
- Generally a bit convoluted and intransparent
- Types for the config object are only being generated after running `yarn start:dev`
- Automagically generating a new file from `node_modules` into the root folder of the current project feels brittle

### **1. Translate the config's JSON schema into TypeScript typings**
The simplest option is likely to just swap out flow for TypeScript using similar package, for example [json-schema-to-typescript](https://www.npmjs.com/package/json-schema-to-typescript) instead of [~~json-schema-to-flow-type~~](https://www.npmjs.com/package/json-schema-to-flow-type)

#### Pros
- Arguably the simple option. We already have the approach, just gotta refactor the output from `.flow` to `.ts`

#### Cons
- No real improvement over the current approach

### **2. Ditch JSON schema and define TypeScript typings via decorators in an object-oriented way**
We could use the TypeScript package [class-validator](https://www.npmjs.com/package/class-validator) and use decorators to define our config schema.

Check out a full example how @barathvk refactored strong-config for his purposes in [bn-config-example](https://gitlab.com/barath.kumar1/bn-config-example)

A config schema using this new approach would look like this:

```ts
import { LoggerOptions } from 'bunyan'
import { Type } from 'class-transformer'
import { IsDefined, IsNumber, Max, Min, ValidateNested } from 'class-validator'

class Server {
  @IsNumber()
  @Min(1024)
  @Max(65535)
  public port: number = 8080
}

export class Config {
  @IsDefined()
  public logger: LoggerOptions

  @IsDefined()
  @ValidateNested()
  @Type(() => Server)
  public server: Server

}
```

This would solve both compile-time validation (via standard TypeScript type checking) as well as runtime validation via [class-validator](https://www.npmjs.com/package/class-validator).

#### Pros
- No need for JSON schema anymore
- Runtime validation included

#### Cons
- Introducing new dependencies & complexities (e.g. now we need [reflect-metadata](https://www.npmjs.com/package/reflect-metadata), slightly more complex TypeScript config)
- Nested validation via the `@ValidateNested()` decorator looks a bit weird and unintuitive compared to a simple nested JSON object

### **3. Ditch JSON schema and define TypeScript typings in a functional way**
This is the most unresearched option yet. But as we're gravitating more towards functional programming. maybe there is an approach to reap the benefits of the above approach without having to define the config object as a class.

Some equivalent to `class-validator` that is functional?

This option would need more exploration.

### **4. Ditch JSON schema and define simple TypeScript types alongside the config object**
This is possibly the most vanilla TypeScript option that would still allow ditching JSON schema. 
Simplified example of a config file with this approach:

```ts
type ConfigT = {
    logger: {
        name: string
        level: 'error' | 'warn' | 'debug'
    }
}

const config: ConfigT = {
    logger: {
        name: 'some-service',
        level: 'error'
    }
}
```

#### Pros
- No need for JSON schema anymore
- Vanilla TypeScript approach
- No new dependencies

#### Cons
- No runtime validation, would need another mechanism for this

**Comment by chapati23** [comment]
test

**Comment by mohoff** [comment]
I prefer option 1 as I see some drawbacks for option 2:

1. All users of `strong-config` who want to have a schema are forced to use Typescript. Option 1 is less opinionated, more flexible and generic.
2.  Having the schema in a TS Class structure seems artificial. Is `class-validator` more used to constraint an object's behaviour/lifecycle? Does not seem like a good fit for us.
3. Nested definitions are moved to top-level Classes, as can be already seen in the minimal example you gave. With increased schema complexity, this will get very hard to read. A structured JSON/YAML file seems the best candidate here imo.
4. With using `class-validator`, it will be hard to generate a schema from existing config files. This could be an interesting feature for the future.

IMO, we should stick to json-schema and `json-schema-to-typescript` seems like a perfect fit for us.

**Comment by chapati23** [comment]
@mohoff i've added a fourth option, just defining the config schema in vanilla TypeScript. I also forgot to highlight an advantage of option 2: it has built-in runtime validation.

to address your points individually:

1. You're right that using JSON schema would address a larger portion of users due to not requiring TypeScript. I don't agree with the "less opinionated" part that much. JSON schema to me is in the end also just another opinion on how to statically type an object that has its own syntax and rules you'll have to follow.
1. I also don't like this approach too much for the OOP-yness. What makes this so attractive IMO is that it would give us runtime validation for free. But yeah, definitely not a big fan of using classes here 🤔
1. See above, don't like classes here either.
1. True. But arguably the switching cost here would be pretty minimal as we only have a handful of projects that are affected.

@crosby any opinions?

**Comment by mohoff** [comment]
Option 4 only allows for strict types, while json-schema can do much more: dependencies, `oneOf`/etc., and supplementary information, e.g. description and examples. Wouldn't want to ditch any of these.

2. Even without `class-validator`, we have runtime validation by exposing a `validate()` function, which can be called anytime. Also with `class-validator`, you'd have to call a validate function in the code to trigger a validation. Can't spot a key difference or advantage in this regard.

**Comment by chapati23** [comment]
The breadth of features of JSON schema vs. TypeScript is an interesting discussion.

You're probably right that JSON schema is more powerful here (although how wouldn't `oneOf` just be an `enum` in TypeScript?).

Question: Are we currently using any of the advanced features of JSON schema?

> 2. Runtime validation
> Sry, what I meant was that we would no longer need a self-implemented `validate()` function when using `class-validator`. You're right that we can of course always implement our own runtime validation

**Comment by crosby** [comment]
My 2 cents:

1. JSON Schema is a great way to validate JSON which is exactly what we want here
2. Generating Typescript types from the JSON schema is just a nice way to help Typescript users keep their codebase strictly typed

So, option 1 would be my preferred solution.

**Comment by chapati23** [comment]
Aight, then let's go with option 1 @mohoff !

**Comment by chapati23** [comment]
@mohoff I think we can consider this one done after merging your first PR, right? (except the README but there's a separate ticket for that).

Will close, reopen if you feel there's still something missing.
