### ISSUE TITLE
Set up CI pipeline

### ISSUE THREAD

**Issue by chapati23** [strong-config/node#2]
### Description
As this is our first public project where GitHub is the source of truth (and not simply a GitLab-mirror as was in the past), we need to decide on the right approach for us to handle CI/CD in this context. And then implement it.

### Tasks
- [ ] Evaluate various CI approaches, add pros & cons for each approach
- [ ] Decide for a CI approach for all `@strong-config` GitHub repos
- [ ] Implement CI in a DRY and sustainable way

### Possible Approaches
There are many options to choose from:
* Keep CI in our GitLab runners but trigger from GitHub via [GitHub Actions](https://github.com/features/actions) (which is unfortunately still in closed beta and I'm still on the waiting list...)
* Use standard hosted gitlab.com runners via [GitLab CI/CD for GitHub](https://about.gitlab.com/solutions/github/)
* Use another CI tool that is free for open source (e.g. [Travis CI](https://travis-ci.org))
* Maybe there are more options..

**Comment by chapati23** [comment]
@mohoff i believe this will count as "done" after merging #5

could you do me a favor and try out some github magic and add `fixes #2` to your PR description? curious to see whether that will auto-close this issue

**Comment by mohoff** [comment]
saw this too late. Yes, it's done.

CI will be further improved in https://github.com/strong-config/node/issues/13 though
