### ISSUE TITLE
Migrate code from internal GitLab to GitHub

### ISSUE THREAD

**Issue by chapati23** [strong-config/node#3]
### Description
After we've set up a CI pipeline, we should migrate the official source of truth for the Strong Config code base from our internal GitLab to this GitHub org.

### Tasks
- [x] Migrate [strong-config codebase](https://git.brickblock.sh/devops/strong-config)
- [ ] Archive repo in GitLab
- [ ] Have all involved devs update their origin via `git remote set-url origin github.com/etc`

### Dependencies
We first need to set up a CI pipeline (#2)

**Comment by chapati23** [comment]
Also closing this one, was more of a general placeholder ticket. I'd consider it done as the source of truth is GitHub now which was the main intention of this ticket.
