### ISSUE TITLE
Add support for a `base.yml` allowing shared default values between environments

### ISSUE THREAD

**Issue by chapati23** [strong-config/node#4]
### Description
Sometimes a value is the same across all environments _except one_ (for example the log level may be `error` across all environments except in development it is `debug`). Currently, we have to copy-paste these shared values manually across `development.yml`, `staging.yml`, `production.yml` etc.

This ticket is about adding support to allow environments to extend from a `base.yml`.

### Caveat
`base.yml` can NOT contain secrets because it's unclear which key to encrypt it with. Let's say you had a `development`, a `staging`, and a `production` environment. I can't think of an elegant way for `strong-config` to know which encryption key to use for `base.yml`.

### Requirements
- [x] If `base.yml` does NOT exist, everything should continue to work as is
- [x] If `base.yml` exists, all configs should extend from it
- [x] Environment-specific configs should take precedence over defaults (e.g. if there are different values for `logLevel` in `base.yml` and `production.yml`, then `production.yml` should win)
- [x] If a value exists in `base.yml`, environment-specific configs can safely omit it (unless they want to override it)

### ToDos
- [x] Add `loadBaseConfig()` and integrate it into `loadConfigFromPath()` and `loadConfigForEnv()`
- [x] Extend unit tests for `loadConfigFromPath()` and `loadConfigForEnv()` with a `describe('with a base config')` 
- [x] Validate that `base.yml` doesn't contain secrets, throw error if secret is detected with appropriate error msg
- [x] Ensure env-specific configs take precedence over base configs
- [x] Ensure config-merge is a deep-merge
- [x] Add `baseConfig` option to allow customising the filename of `base.yml` (e.g. to `defaults.yml`)
- [x] Add unit tests for `loadBaseConfig()`
- [x] Add integration tests for base config cases
- [x] Add e2e tests for base config cases

**Comment by mohoff** [comment]
Great! Let's deep merge an optional `default.yml` with `<environment>.yml` where the latter always takes precedence.

Edge cases to think of:
- Consider a non-empty `default.yml` and no `<environment>.yml`. Do we want to fail or rather treat the default config as a valid one for all environments?
- Can an environment be named 'default'?

**Comment by chapati23** [comment]
**Empty `<env>.yml`**
I'd say in this case `<env>.yml` is equal to `default.yml`. If that's not desired, then you can always take the value out of the `default.yml`. I think it's safest and simplest to pick the easy universal rule here: `Everything in default.yml is always part of all <env>.yml's`

**Env Name `default`**
Good point. I would say no. The code should error with an informative message of why this is a reserved name and please pick another one.

**Comment by crosby** [comment]
I think it's important to make the distinction between environment configuration and app configuration.

The only values that should appear in environment configuration are values that change between environments. Even if one environment has a different value for a configuration value, it's a candidate for environment configuration.

App configuration is in my opinion the final configuration that is used by the application that contains both general configuraton and environment configuration merged. 

I could image a setup like this:

```
/config/index.js
/config/development.js
/config/staging.js
/config/production.js
```

with `/config/index.js` just containing general app config that doesn't change between environments.

`strong-config` could then combine this app config with the environment's config to generate the final config that you get when you `.load()`.

**Comment by chapati23** [comment]
Sorry @crosby but I'm not sure I got your point. Are you implying we should _not_ add a `default.yml` that other configs extend from?

What about the case of a value being identical for all environments _except_ one? See the log-level example above.

**Comment by barathvk** [comment]
Another issue to keep in mind here is that there is no project for `default`. How would we encrypt this file considering `review` (for example) has only access to decrypt `review.yml` since the `review` project key was used to encrypt that file? We could suggest that `default.yml` must not have any secrets and check that it is not encrypted or even enforce this.

**Comment by mohoff** [comment]
Ah great catch, @barathvk ! I agree, think we can't have secrets in a `default.yml`.

However, a `default.yaml` without secrets can already be valuable. Reconstruct all files when an encrypted `review.yml` is being decrypted should be possible. By comparing `default.yml` and `review.yml`, we can reconstruct the plain text `review.yml`.
